language: php
sudo: false

cache:
    directories:
        - $HOME/.composer

matrix:
    fast_finish: true
    include:
        - php: '7.0'
        #- php: 7.1
        #- php: 7.2
        #- php: nightly

before_install:
    - composer self-update
    - travis_retry wget -O ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
    - chmod +x ~/.phpenv/versions/7.0/bin/phpunit
    - travis_retry wget -O ~/.phpenv/versions/7.0/bin/php-cs-fixer https://cs.symfony.com/download/php-cs-fixer-v2.phar
    - chmod +x ~/.phpenv/versions/7.0/bin/php-cs-fixer

install:
    - composer install

script:
    - make build
