language: php
sudo: false

cache:
    directories:
        - $HOME/.composer

matrix:
    fast_finish: true
    include:
        - php: '7.0'
        #- php: 7.1
        #- php: 7.2
        #- php: nightly

before_install:
    - composer self-update
    - curl -sSfL -o ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
    - travis_retry wget -O ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
    - chmod +x ~/.phpenv/versions/7.0/bin/phpunit

install:
    - composer install

script:
    - make build
